### ISSUE TITLE
support for python-multipart>=0.0.9

### ISSUE THREAD

**Issue by fcakyon** [supervisely/supervisely#1111]
Hello,

I'm grateful for your recent update on supporting recent pydantic and urrllib3 versions!

I'm using [gradio](https://github.com/gradio-app/gradio), which has the dependency of `python-multipart>=0.0.9`, but the latest supervisely version requires `python-multipart==0.0.5`, which makes them clash during `pip install -r requirements.txt`.

Do you have any plans to update the python-multipart dependency version as well? 

cc: @iwatkot

**Comment by iwatkot** [comment]
@fcakyon hello!

Same as for a previous issue, we'll check if it's possible to update the version of dependency and I'll get back to you.

Sincerely

**Comment by fcakyon** [comment]
Fantastic news! @iwatkot
