### ISSUE TITLE
Support drawing arbitrary colors in label.draw

### ISSUE THREAD

**Issue by Jihadik** [supervisely/supervisely#13]
I would like to have an ability to draw arbitrary colors in `Label`'s `draw` method. For example, I have 100 objects on my image 1000x1000. I would like to create an array of size 1000x1000 (without 3-rd component) and put indexes from 1 to 100 on it corresponding to my objects, the background will be zero.

I hacked your `draw` method to this one:
```py
    def draw(self, bitmap, color=None, thickness=1, draw_tags=False, tags_font=None):
        color = self.obj_class.color if color is None else color
        self.geometry.draw(bitmap, color, thickness)
        if draw_tags:
            self._draw_tags(bitmap, tags_font)
```
and it works correctly, but I'm pretty sure it will break something, so I'm leaving the change to you.

**Comment by antonc-ds** [comment]
Hi @Jihadik , thanks for the suggestion! That's exactly the fix, we are not passing thickness positionally anywhere in the codebase AFAICT, so nothing should break. Added this as a part of 21451073c44fa844446f397433bdce96634a8010.

**Comment by Jihadik** [comment]
Lovely, thanks @antonc-ds!
