### ISSUE TITLE
Machine masks folder contains all-black images

### ISSUE THREAD

**Issue by vijpandaturtle** [supervisely/supervisely#16]
Hi, i'm using supervisely to annotate a dataset of mine. When i try to download png masks of the dataset, all i get is a folder with each image that's completely black. Is there something i'm doing wrong ? I need some help. Thanks

**Comment by breezykermo** [comment]
The images in machine masks generally look just black from a distance. The
machine masks use a slightly different dark gray color of pixels for the
annotation that is very close to black. If you zoom in on one of the images
around its annotation, you may be able to see that its pixels differ
slightly from the background black pixels.



Il dom 30 giu 2019, 08:51 Vijayasri Iyer <notifications@github.com> ha
scritto:

**Comment by vijpandaturtle** [comment]
@breezykermo I see. Also, what is the thickness parameter that I have to specify before downloading the masks ?

**Comment by breezykermo** [comment]
I'm not sure sorry, I'm not familiar with that feature.

**Comment by antonc-ds** [comment]
Hi @vijpandaturtle . The `thickness` parameter determines the brush thickness for drawing lines and points. It is typically useful for high-resolution images, where with a default 1-pixel thickness the lines and points in the mask are often barely visible. If you only have bitmaps, polygons and rectangles in your annotation, the parameter does not make any difference.

Also, for the machine colors, as @breezykermo said, we are using brightness levels starting from 1 and up, so the images look black to the eye when there are few classes in the annotation. You can find the mapping from class name to the color used in the machine masks in `obj_class_to_machine_color.json` file that is a part of the downloaded project.

The code that forms the download archive is here: https://github.com/supervisely/supervisely/blob/master/plugins/python/src/download_image_masks.py if you need to find out exactly what is going on.

**Comment by vijpandaturtle** [comment]
No issues @breezykermo 
Thanks a lot @antonc-ds :)

**Comment by kdh4672** [comment]
@antonc-ds 
I still cannot understand about thickness.
when i extract polygon mask from my project, there are no difference between thickness = 1 and thickness = 100.
can you explain about thickness at supervisely more detaily?

**Comment by antonc-ds** [comment]
Hi @kdh4672. I am not involved with the project anymore, sorry. Maybe @mkolomeychenko can help you with the details.
