### ISSUE TITLE
Support specifying description in project meta

### ISSUE THREAD

**Issue by al-muammar** [supervisely/supervisely#17]
On supervisely website inside each project classes one could specify descriptions for them. Unfortunately, it's not supported neither on API [nor on the library level](https://github.com/supervisely/supervisely/blob/master/supervisely_lib/annotation/obj_class.py#L30).

It would be a nice feature, if we could specify descriptions programmatically.

**Comment by Jihadik** [comment]
@antonc-ds, any updates here? That would be a really nice feature for us.
