### ISSUE TITLE
Accept colors in hex

### ISSUE THREAD

**Issue by al-muammar** [supervisely/supervisely#18]
Currently, if one would like to create an `ObjClass`, he should pass the color as a list of ints. Here is a short function that will help you to convert from hex to a list of ints:
```py
def hex2rgb(string: str) -> List[int]:
    h = string.lstrip("#")
    return list(int(h[i : i + 2], 16) for i in (0, 2, 4))
```

If you could support it on your side, that would be great.

**Comment by antonc-ds** [comment]
Hi @Jihadik, thanks for the suggestion! We actually have the converter here: https://github.com/supervisely/supervisely/blob/67069fb8b6b04ba320b5ab374b78eff283b104a7/supervisely_lib/imaging/color.py#L84

Did you mean here just adding the converter, or making the color argument support both list and hex-string representation too?

**Comment by Jihadik** [comment]
I meant accepting both hex and list representations.
