### ISSUE TITLE
no right result when I run 02_unet_inference 

### ISSUE THREAD

**Issue by zy2008cn** [supervisely/supervisely#2]
Thanks to the open source!!!  I follow the tutorials to run 02_unet_inference, and download UNetV2(legacy) model and config from https://app.supervise.ly/models/my. When all the environment are down , but I cann't get right result. In the annotation mask, no person or road objects can be found.

**Comment by zy2008cn** [comment]
Looking forward to your reply!

**Comment by zy2008cn** [comment]
Hope for your reply.

**Comment by antonc-ds** [comment]
Sorry for dropping the ball on this. We have not monitored the issues section systematically previously and missed the question. Will close this since it has been a very long time, so likely does not matter anymore..
