### ISSUE TITLE
Bug in pascal_vot_writer

### ISSUE THREAD

**Issue by hlacik** [supervisely/supervisely#21]
You have a bug in pascal_voc.py (export to VOC), when writing VOC file using pascal_voc_writer

path should be path to image file, but you are using path to export folder, which causes that all exported VOC xmls contains in tag <filename> wrong attribute , and not image filename

**wrong :**

`            writer = pascal_voc_writer.Writer(path=pascal_dataset_relative_path,
                                              width=ann.img_size[1],
                                              height=ann.img_size[0])`

**correct**

` writer = pascal_voc_writer.Writer(path=pascal_img_path,
                                              width=ann.img_size[1],
                                              height=ann.img_size[0])`

**Comment by antonc-ds** [comment]
Hi @hlacik, thank you for the bug report! We have pushed a fix in 445c7166049b740fb0f2285889f95062e7de231a . Thanks!
