### ISSUE TITLE
Canonical citation

### ISSUE THREAD

**Issue by Lodinn** [supervisely/supervisely#255]
Hi,

Given your work keeps gaining traction in the academic community, could you please provide a "how to cite" section either in the README or the website itself? I might be blind, but I could not find one.

You might not care about the academic accolades, but this would save a lot of hassle for scientists using your tool and, eventually, increase the exposure the platform has.

Currently, the best I could find on Google Scholar was
Drozdov, D.; Kolomeychenko, M.; Borisov, Y. Supervisely. Available online: https://www.supervise.ly,
but it might not reflect your opinion on how it should be credited. More importantly, a good share of researchers seem to opt for in-text links to avoid the citation issue altogether.

Cheers!

**Comment by mkolomeychenko** [comment]
thank you for the suggestion and sorry for the long reply. Here it is: https://github.com/supervisely/supervisely#cite-this-project
