### ISSUE TITLE
Annotation format

### ISSUE THREAD

**Issue by simonepignotti** [supervisely/supervisely#3]
Hi,
Congratulations for your work, I love how supervisely makes it easy to annotate datasets and test new models on the fly, and I really appreciate your effort to make it open source.
I believe it would be extremely useful to be able to export the dataset annotations in a standard format, e.g. [COCO](http://cocodataset.org/#format-data)'s. As you already have the code to import COCO annotations, it should not be too difficult to reverse it and convert your custom format to COCO. This would allow users to test other solutions ([Detectron](https://github.com/facebookresearch/Detectron), for instance) without the conversion hassle, and may result in supervisely becoming THE reference for annotation.
Thanks in advance for your time.

Simone

**Comment by antonc-ds** [comment]
Thanks @simonepignotti for the suggestions. Sorry for the delay, we have not been checking the issues here systematically (we will from now on though). We are working on COCO export. We already have Pascal VOC export implemented in the SDK (https://github.com/supervisely/supervisely/blob/master/supervisely_lib/export/pascal_voc.py), COCO format is next in line.

**Comment by hlacik** [comment]
I would really love to have coco as well!

**Comment by ruodingt** [comment]
Same here.  Coco make life easier.

**Comment by burnmyletters** [comment]
Did someone succeed with Coco conversion?

**Comment by caiofcm** [comment]
I created this conversion script, but only concerning the detection (bbox). Should be OK to add other fields.

https://gist.github.com/caiofcm/0b93b0084669a1287633d9ebf32f3833

**Comment by gireeshkbogu** [comment]
Did anyone use supervisely annotations to run a segmentation task in PyTorch?

**Comment by TemitopeOladokun** [comment]
Hello everyone,
I convert the Supervisely JSON to COCO but lost some instance. Has anyone encountered such an error and how did you fix it?
@caiofcm @burnmyletters @ruodingt @hlacik @simonepignotti

**Comment by apockill** [comment]
I have also encountered such errors actually! I always assumed it was because of my conversion script, but now I have second thoughts...

**Comment by TemitopeOladokun** [comment]
Kindly share how did you fixed it @antonc-ds ? 


> Hello everyone,
> I convert the Supervisely JSON to COCO but lost some instance. Has anyone encountered such an error and how did you fix it?
> @caiofcm @burnmyletters @ruodingt @hlacik @simonepignotti

Kindly share how did you fixed it @antonc-ds ?

**Comment by TemitopeOladokun** [comment]
Thank you @antonc-ds for your guide.

**Comment by gembancud** [comment]
Hi i'd like to ask why the cocostuff [plugin ](https://github.com/supervisely/supervisely/tree/master/plugins/import/cocostuff)was removed since I cant find it anywhere to easily import my coco formatted dataset?

**Comment by borgarpa** [comment]
> 
> 
> Hi i'd like to ask why the cocostuff [plugin ](https://github.com/supervisely/supervisely/tree/master/plugins/import/cocostuff)was removed since I cant find it anywhere to easily import my coco formatted dataset?

I was wondering the same... When will COCO plugin be ready again?
