### ISSUE TITLE
downloading datasets seems to have a bug?

### ISSUE THREAD

**Issue by NoNamesLeft4Me** [supervisely/supervisely#36]
Env: Windows 10, Python 3.7.0, numpy 1.18.2

I am trying to download a data from Supervisely to local directory following the tutorial script in [/download_project/download_project.ipynb](https://github.com/supervisely/supervisely/blob/master/help/jupyterlab_scripts/src/cookbook/download_project/download_project.ipynb)

There was an error when I ran the code of `project = api.project.get_info_by_name(workspace.id, project_name)`
I found out the issue is that the `project ` dict does not have a keyword of `'type'`,  and the code runs into a problem when  `_convert_json_info(self, info: dict, skip_missing=False)` is called in supervisely_lib/api/module_api.py.

So I change `_convert_json_info(self, info: dict, skip_missing=False)` to `_convert_json_info(self, info: dict, skip_missing=True)` and it seems working. 

I am wondering if this is a bug or I did something wrong.

**Comment by mkolomeychenko** [comment]
Thank you for the report, will check it!

**Comment by mkolomeychenko** [comment]
it is fixed, thank you! 

6ab9710b6d6eb9227ffd8c40218bc5d15ae5a9ec
