### ISSUE TITLE
Windows support for supervise.ly agent

### ISSUE THREAD

**Issue by anandcu3** [supervisely/supervisely#4]
Is there a possibility of installing the agent of windows  machine? If not, will it be supported in the future.

Thanks

**Comment by antonc-ds** [comment]
Hi @anandcu3 . Windows support is unlikely unfortunately. We have looked at accessing CUDA from inside a Windows Docker Linux-based container, and apparently this is highly nontrivial at the very least. So for now we will focus more on other useful features that do not require as much effort. We may come back to this at some point, especially if there are significant developments into Linux-Docker-Windows interop, but no definite plans for now.
