### ISSUE TITLE
Tablet compatibility

### ISSUE THREAD

**Issue by ctr26** [supervisely/supervisely#492]
Hi all,

not sure if this is a known issue but the interface struggles when used on a tablet and more so when using an Apple Pencil

thanks

**Comment by iwatkot** [comment]
Hello!
We're kindly asking our users to request help and support via our Slack channel: https://supervisely.com/slack/ or e-mail: [support@supervisely.com](mailto:support@supervisely.com).

Regarding your question, we're aware of this issue and planning to add tablet support soon.


Thank you for understanding and sorry for the late reply.
