### ISSUE TITLE
Additional Config Options for Video plugin

### ISSUE THREAD

**Issue by sgallagher924** [supervisely/supervisely#6]
This is a possible enhancement request.
In some situations it might be nice to be able to provide additional config options then just the step on the video plugin. I checked the code for the plugin and it seems to only look for and consider the 'step' option. Some examples of possible configs could include, excluding specific frames, a frame to start stepping from, etc.

**Comment by apockill** [comment]
IMO a hugely useful addition would be adding a dhash
<https://pypi.org/project/dhash/> distance parameter, so that you can
extract only unique frames from the videos.

**Comment by antonc-ds** [comment]
Thanks @sgallagher924 and @apockill for the suggestions! We will definitely look at adding the dhash distance to the logic.

**Comment by antonc-ds** [comment]
Added in https://github.com/supervisely/supervisely/commit/a8f6bc274d08138ce6b6341f9c5d56e916d4b112 these options:
```
start_frame
end_frame
skip_frames
dhash_min_hamming_distance
```
