### ISSUE TITLE
Print api request error details

### ISSUE THREAD

**Issue by YaroslavSchubert** [supervisely/supervisely#8]
It would be nice to see the details of the API request error if an exception is not retriable.

https://github.com/supervisely/supervisely/blob/master/supervisely_lib/api/api.py#L79

**Comment by antonc-ds** [comment]
Yup, good point, on our stack.

**Comment by antonc-ds** [comment]
Added detailed logging in https://github.com/supervisely/supervisely/commit/a8f6bc274d08138ce6b6341f9c5d56e916d4b112
